//! Raw Arrow batch iterator for streaming results from raw/stored procedure queries.
//!
//! This module provides iterators for streaming Arrow RecordBatches from raw query results,
//! such as Oracle PL/SQL blocks or MSSQL stored procedures that return result sets via
//! implicit cursors.
//!
//! Unlike the standard `ArrowBatchIter` which uses ConnectorX's parallel query execution,
//! these iterators work with single-threaded raw query execution for cases where
//! parallelism isn't applicable (e.g. stored procedures).

use arrow::error::ArrowError;
use arrow::record_batch::RecordBatch;

use crate::destinations::arrowstream::ArrowDestinationError;

// ============================================================================
// Error Types
// ============================================================================

/// Error type for raw Arrow streaming operations.
///
/// This error type is generic and can wrap errors from any source that implements
/// `RawSource`. Source-specific errors are stored as boxed trait objects.
#[derive(Debug)]
pub enum RawArrowError {
    /// Error from a data source (boxed for generic handling)
    Source(Box<dyn std::error::Error + Send + Sync>),
    /// Error from Arrow operations
    Arrow(ArrowError),
    /// Error from Arrow destination
    ArrowDestination(ArrowDestinationError),
    /// Error from ConnectorX
    ConnectorX(crate::errors::ConnectorXError),
    /// Generic error
    Other(String),
}

impl std::fmt::Display for RawArrowError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RawArrowError::Source(e) => write!(f, "Source error: {}", e),
            RawArrowError::Arrow(e) => write!(f, "Arrow error: {}", e),
            RawArrowError::ArrowDestination(e) => write!(f, "Arrow destination error: {}", e),
            RawArrowError::ConnectorX(e) => write!(f, "ConnectorX error: {}", e),
            RawArrowError::Other(e) => write!(f, "Error: {}", e),
        }
    }
}

impl std::error::Error for RawArrowError {}

impl From<ArrowError> for RawArrowError {
    fn from(e: ArrowError) -> Self {
        RawArrowError::Arrow(e)
    }
}

impl From<ArrowDestinationError> for RawArrowError {
    fn from(e: ArrowDestinationError) -> Self {
        RawArrowError::ArrowDestination(e)
    }
}

impl From<crate::errors::ConnectorXError> for RawArrowError {
    fn from(e: crate::errors::ConnectorXError) -> Self {
        RawArrowError::ConnectorX(e)
    }
}

impl From<String> for RawArrowError {
    fn from(e: String) -> Self {
        RawArrowError::Other(e)
    }
}

// ============================================================================
// Generic Raw Arrow Batch Iterator
// ============================================================================

use crate::data_order::DataOrder;
use crate::destinations::arrowstream::{ArrowDestination, ArrowPartitionWriter, ArrowTypeSystem};
use crate::destinations::{Destination, DestinationPartition};
use crate::sources::{PartitionParser, RawSource};
use crate::typesystem::RawTransport;
use arrow::datatypes::Schema;
use std::fmt::Debug;
use std::marker::PhantomData;
use std::sync::Arc;

/// Default batch size for Arrow record batches
const DEFAULT_BATCH_SIZE: usize = 1024;

/// Function pointer type for raw processors.
/// These are generated by `RawTransport::raw_processor` and handle both
/// type conversion and value transfer from parser to writer.
type RawProcessorFn<S, TP> = fn(
    &mut <S as RawSource>::Parser,
    &mut ArrowPartitionWriter,
) -> Result<(), <TP as crate::typesystem::Transport>::Error>;

/// Generic iterator over raw query results (PL/SQL blocks, stored procedures) as Arrow RecordBatches.
///
/// This iterator executes a raw query and yields RecordBatches. It's designed for queries
/// that return result sets via implicit cursors (e.g., `dbms_sql.return_result` in Oracle,
/// or stored procedures in MSSQL).
///
/// This implementation uses `RawTransport` to apply the same type conversions as the
/// standard ConnectorX pipeline, ensuring consistent behavior between standard and raw queries.
///
/// # Type Parameters
/// * `S` - The source type, must implement `RawSource`
/// * `TP` - The transport type, must implement `RawTransport`
///
/// # Example
///
/// ```ignore
/// use connectorx::prelude::*;
///
/// // For Oracle:
/// let source = OracleSource::new("oracle://user:pass@host:1521/db", 1)?;
/// let query = r#"
///     declare
///       cursor1 SYS_REFCURSOR;
///     begin
///       cursor1 := get_all_users();
///       dbms_sql.return_result(cursor1);
///     end;
/// "#;
///
/// let mut iter = RawArrowBatchIterator::<OracleSource, OracleArrowStreamTransport>::new(source, query)?;
/// iter.prepare()?;
///
/// for batch_result in iter {
///     let batch = batch_result?;
///     println!("Got {} rows", batch.num_rows());
/// }
/// ```
pub struct RawArrowBatchIterator<S, TP>
where
    S: RawSource,
    TP: RawTransport<TSS = S::TypeSystem, TSD = ArrowTypeSystem, S = S, D = ArrowDestination>,
{
    parser: S::Parser,
    destination: ArrowDestination,
    writer: Option<<ArrowDestination as Destination>::Partition<'static>>,
    /// Processor function pointers for each column.
    /// Built at construction time using `RawTransport::raw_processor`.
    /// These include type conversion logic from the transport.
    processors: Vec<RawProcessorFn<S, TP>>,
    arrow_schema: Arc<Schema>,
    is_finished: bool,
    pending_rows: usize,
    _phantom: PhantomData<TP>,
}

impl<S, TP> RawArrowBatchIterator<S, TP>
where
    S: RawSource,
    S::Error: std::error::Error + Send + Sync + 'static,
    TP: RawTransport<TSS = S::TypeSystem, TSD = ArrowTypeSystem, S = S, D = ArrowDestination>,
    TP::Error: Debug + Send,
{
    /// Create a new iterator for a raw query.
    ///
    /// # Arguments
    /// * `source` - A source with a connection pool
    /// * `query` - The raw query (e.g., PL/SQL block, stored procedure call) to execute
    pub fn new(source: S, query: &str) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        Self::new_with_batch_size(source, query, DEFAULT_BATCH_SIZE)
    }

    /// Create a new iterator with a custom batch size.
    ///
    /// # Arguments
    /// * `source` - A source with a connection pool
    /// * `query` - The raw query (e.g., PL/SQL block, stored procedure call) to execute
    /// * `batch_size` - Number of rows per RecordBatch
    pub fn new_with_batch_size(
        mut source: S,
        query: &str,
        batch_size: usize,
    ) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        // Execute raw query and get parser with schema
        let (parser, names, source_types) = source.execute_raw_query(query)?;

        // Convert source types to Arrow types using the transport's mapping
        let arrow_types: Vec<ArrowTypeSystem> = source_types
            .iter()
            .map(|&t| TP::convert_typesystem(t))
            .collect::<Result<Vec<_>, crate::errors::ConnectorXError>>()?;

        // Build processor function pointers using RawTransport::raw_processor.
        let processors: Vec<RawProcessorFn<S, TP>> = source_types
            .iter()
            .zip(arrow_types.iter())
            .map(|(&src_type, &dst_type)| TP::raw_processor(src_type, dst_type))
            .collect::<Result<Vec<_>, crate::errors::ConnectorXError>>()?;

        // Create ArrowDestination with the schema
        let mut destination = ArrowDestination::new_with_batch_size(batch_size);
        destination.allocate(0, &names, &arrow_types, DataOrder::RowMajor)?;

        // Get the Arrow schema before taking ownership of writer
        let arrow_schema = destination.arrow_schema();

        // Create partition writer
        let mut writers = destination.partition(1)?;
        let writer = writers.pop().unwrap();

        // We need to use unsafe to extend the lifetime of the writer
        // This is safe because we ensure the destination outlives the writer
        // by keeping both in the same struct
        let writer: <ArrowDestination as Destination>::Partition<'static> =
            unsafe { std::mem::transmute(writer) };

        Ok(Self {
            parser,
            destination,
            writer: Some(writer),
            processors,
            arrow_schema,
            is_finished: false,
            pending_rows: 0,
            _phantom: PhantomData,
        })
    }

    /// Get the Arrow schema for this result set.
    pub fn schema(&self) -> Arc<Schema> {
        self.arrow_schema.clone()
    }

    /// Prepare the iterator by fetching the first batch of rows.
    ///
    /// Call this before iterating to ensure data is ready.
    pub fn prepare(&mut self) -> Result<(), RawArrowError> {
        if self.pending_rows == 0 && !self.is_finished {
            let (n, finished) = self
                .parser
                .fetch_next()
                .map_err(|e| RawArrowError::Source(Box::new(e)))?;
            self.pending_rows = n;
            self.is_finished = finished && n == 0;
        }
        Ok(())
    }

    /// Process pending rows through the writer using RawTransport processor functions.
    fn process_rows(&mut self, nrows: usize) -> Result<(), RawArrowError> {
        let writer = self
            .writer
            .as_mut()
            .ok_or_else(|| RawArrowError::Other("Writer already finalized".to_string()))?;

        for _ in 0..nrows {
            for processor in &self.processors {
                processor(&mut self.parser, writer)
                    .map_err(|e| RawArrowError::Other(format!("{:?}", e)))?;
            }
        }
        Ok(())
    }
}

impl<S, TP> Iterator for RawArrowBatchIterator<S, TP>
where
    S: RawSource,
    S::Error: std::error::Error + Send + Sync + 'static,
    TP: RawTransport<TSS = S::TypeSystem, TSD = ArrowTypeSystem, S = S, D = ArrowDestination>,
    TP::Error: Debug + Send,
{
    type Item = Result<RecordBatch, RawArrowError>;

    fn next(&mut self) -> Option<Self::Item> {
        // First, check if there are any batches already available
        if let Some(batch) = self.destination.try_record_batch() {
            return Some(Ok(batch));
        }

        // If we have pending rows, process them
        if self.pending_rows > 0 {
            let nrows = self.pending_rows;
            self.pending_rows = 0;

            if let Err(e) = self.process_rows(nrows) {
                return Some(Err(e));
            }

            // Check if processing produced any batches
            if let Some(batch) = self.destination.try_record_batch() {
                return Some(Ok(batch));
            }
        }

        // Check if we're finished
        if self.is_finished {
            // Finalize the writer to flush any remaining data
            if let Some(mut writer) = self.writer.take() {
                if let Err(e) = writer.finalize() {
                    return Some(Err(RawArrowError::ArrowDestination(e)));
                }
            }
            // Get any remaining batches
            return self.destination.try_record_batch().map(Ok);
        }

        // Fetch more rows
        match self.parser.fetch_next() {
            Ok((n, finished)) => {
                self.is_finished = finished;

                if n == 0 {
                    // No more rows, finalize
                    if let Some(mut writer) = self.writer.take() {
                        if let Err(e) = writer.finalize() {
                            return Some(Err(RawArrowError::ArrowDestination(e)));
                        }
                    }
                    return self.destination.try_record_batch().map(Ok);
                }

                // Process the fetched rows
                if let Err(e) = self.process_rows(n) {
                    return Some(Err(e));
                }

                // Return any batch that was produced
                if let Some(batch) = self.destination.try_record_batch() {
                    Some(Ok(batch))
                } else if finished {
                    // If finished but no batch yet, finalize to flush remaining
                    if let Some(mut writer) = self.writer.take() {
                        if let Err(e) = writer.finalize() {
                            return Some(Err(RawArrowError::ArrowDestination(e)));
                        }
                    }
                    self.destination.try_record_batch().map(Ok)
                } else {
                    // Continue fetching - call next recursively
                    self.next()
                }
            }
            Err(e) => {
                self.is_finished = true;
                Some(Err(RawArrowError::Source(Box::new(e))))
            }
        }
    }
}

// ============================================================================
// Database-Specific Type Aliases for Convenience
// ============================================================================

/// Type alias for Oracle raw query iterator.
///
/// This provides backwards compatibility and a convenient shorthand for Oracle users.
#[cfg(all(feature = "src_oracle", feature = "dst_arrow"))]
pub type OracleRawRecordBatchIterator = RawArrowBatchIterator<
    crate::sources::oracle::OracleSource,
    crate::transports::OracleArrowStreamTransport,
>;

// Future: Add MSSQL type alias when MSSQL RawSource is implemented
// #[cfg(feature = "src_mssql")]
// pub type MsSqlRawRecordBatchIterator = RawArrowBatchIterator<
//     crate::sources::mssql::MsSqlSource,
//     crate::transports::MsSqlArrowStreamTransport,
// >;
